# SPDX-FileCopyrightText: 2026 Melvin Keskin <melvo@olomono.de>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

# Automatically merged translation files.
[[annotations]]
path = "poqm/**"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "GPL-3.0-or-later"
